before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.date={{.Date}} -X main.commit={{.ShortCommit}} -X main.builtBy=goreleaser
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.build={{.Version}} -X main.date={{.Date}} -X main.commit={{.ShortCommit}} -X main.builtBy=goreleaser
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
brews:
  - name: crzy
    tap:
      owner: go-crzy
      name: homebrew-crzy
    commit_author:
      name: Gregory
      email: 10611760+gregoryguillou@users.noreply.github.com
    folder: Formula
    homepage: "https://github.com/go-crzy/crzy"
    description: "deploy your tests in less than 3 seconds."
    license: "Apache-2.0"
    dependencies:
      - name: git
      - name: go
    install: |
      bin.install "crzy"
