main:
  head: main
  server: true
  color: true
  repository: myrepo
  api_port: 8080
  proxy_port: 8081

trigger:
  version:
    command: git
    args:
    - log
    - "-1"
    - "--format=%H"
    - "."
    workdir: "."
  
deploy:
  artifact:
    type: executable
    pattern: go-${version}
  build:
    command: go
    args:
    - build
    - "-o"
    - ${artifact}
    - "."
    workdir: "."
  test:
    command: go
    args: 
    - test
    - "./..."
    workdir: "."
