version: 2.1
workflows:
  main:
    jobs:
      - build
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

